### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/raspberrypi-homeserver#30]
- [ ] Bug fixes
- [x] Add disk mount

**Comment by veerendra2** [comment]
* Filebrowser 
![image](https://user-images.githubusercontent.com/8393701/200188964-865f1b82-9b3e-46ee-a029-124f518f94fb.png)

**Comment by veerendra2** [comment]
Except `portainer`, all excepts are due to https://github.com/veerendra2/raspberrypi-homeserver/issues/15

**Comment by veerendra2** [comment]
## Jellyfin
`docker-compose.yml`
```
---
version: "3"

volumes:
  jellyfin:

networks:
  front-tier:
    external: true

services:
  jellyfin:
    build: .
    container_name: jellyfin
    hostname: jellyfin.local
    env_file:
      - .env
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - /media/disk1/movies:/movies:ro
      - /media/disk1/tvshows:/tvshows:ro
      - jellyfin:/config
      - jellyfin:/cache
    restart: "unless-stopped"
    networks:
      - front-tier
```
`Dockerfile`
```
FROM jellyfin/jellyfin:10.8.5
COPY config/network.xml /config/config/network.xml
```
