### ISSUE TITLE
Web file browser Deployment

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/raspberrypi-homeserver#9]
- [ ] Web file browser Deployment via `docker-compose`

#### Links
https://github.com/filebrowser/filebrowser

**Comment by veerendra2** [comment]
Docker compose file
```
version: '3'

networks:
  front-tier:
    external: true

services:
  filebrowser:
    image: hurlenko/filebrowser:v2.22.3
    user: "${UID}:${GID}"
    container_name: filebrowser
    hostname: filebrowser
    env_file:
      - .env
    ports:
      - 8080
    volumes:
      - /media/filebrowser:/data
      - ./config:/config
    restart: unless-stopped
    networks:
      - front-tier
```

```
$ docker-compose up
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
Pulling filebrowser (hurlenko/filebrowser:v2.22.3)...
v2.22.3: Pulling from hurlenko/filebrowser
b3c136eddcbf: Already exists
939b282a3dbd: Pull complete
76ece356c9de: Pull complete
Digest: sha256:f9683bf9c0182efa6dc7dea1cb7ccb8795a37fc231e4ab17f0b340e97ae81005
Status: Downloaded newer image for hurlenko/filebrowser:v2.22.3
Recreating filebrowser ... done
Attaching to filebrowser
filebrowser    | 2022/10/09 13:23:35 No config file used
filebrowser    | 2022/10/09 13:23:35 Listening on [::]:8080
filebrowser    | 2022/10/09 13:23:40 //index.html: 404 192.168.0.48 <nil>
filebrowser    | 2022/10/09 13:24:18 //index.html: 404 192.168.0.48 <nil>
filebrowser    | 2022/10/09 13:24:21 //index.html: 404 192.168.0.48 <nil>
```
